### ISSUE TITLE
unable to "docker login" to a private repo

### ISSUE THREAD

**Issue by carljmosca** [iron-io/ironcli#58] opened 2015-12-28 04:05 UTC
I have a private Docker repo (V2) at artifactoryonline.com

I can "docker login" to the repo but "iron docker login ..." fails with "Docker repo auth failed"

I am doing this:

```
iron docker login -e EMAIL_ADDRESS -p PASSWORD -u USERNAME -url https://COMPANY-dockerdockerv2-local.artifactoryonline.com/v2/
```

(with actual values for upper-cased variables)

suggestions?

**Comment by carljmosca** [comment] 2015-12-28 17:42
This appears to be a V1 vs V2 issue.  Removing the "users/" from call to http.NewRequest() in commands.go around line 494 allows me to login.  I am also able to do a "register".

However, when I try to "work queue..." it fails with image not found.

**Comment by rdallman** [comment] 2015-12-31 18:47
hi @carljmosca thanks for raising this issue. by removing `users/` from the URL you are doing a GET against the root for `https://COMPANY-dockerdockerv2-local.artifactoryonline.com/v2/` rather than attempting to authenticate your user. this basically bypasses our verification that you passed us valid docker credentials. 

What I'd like to do to resolve this issue is two fold:

1) I'd like to stop doing verification of the docker registry credentials client side and move it into our servers so that 'image not found' would be caught when trying to give us docker credentials, rather than at queue time (this was the original intent, but it's now obvious how to bypass this: simply use raw API to get any docker registry creds the user wishes stored, even if they won't work later). 

2) resolve V1 vs V2 api disparities in performing the authentication of credentials, and add support for authenticating 'v2' of the registry api. I believe the issue is that we only played nice with v1, which is now deprecated, so we should move to supporting v2. 

We will get started on this and post updates back to this issue. Thanks again

**Comment by carljmosca** [comment] 2015-12-31 18:55
Hello @rdallman 

I am not certain I was able to get the commercially-hosted private V1 Docker repo working with or without iron.io.

I do know the V2 one works nicely for us and I look forward to trying it again with iron.io once this update is available.

Thank you for the quick follow up (especially given the holidays) and for a nice user experience/support in general.

Regards and Happy New Year!!
Carl

**Comment by rdallman** [comment] 2016-10-13 22:52
this is fixed and pending release now, closing. took long enough!

**Closed by rdallman** 2016-10-13 22:52 UTC
